# Nombre del servicio
spring.application.name=GATEWAY-SERVICE

server.port=8080

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Spring Cloud Gateway routes
spring.cloud.gateway.routes[0].id=zone-config-service
spring.cloud.gateway.routes[0].uri=lb://ZONE-CONFIG-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/zone-config-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=flow-audit-service
spring.cloud.gateway.routes[1].uri=lb://FLOW-AUDIT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/flow-audit-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
